# longdcam frontend
server {
    listen 80;
    listen 443 ssl;
    server_name longdcam-front.ghmate.com;
    ssl_certificate /etc/nginx/certs/cloudflare_chain.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;

    location / {
        proxy_pass http://longdcam_front_prod:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# longdcam API + Socket.IO (network_mode: host, so use Docker gateway)
server {
    listen 80;
    listen 443 ssl;
    server_name longdcam-back.ghmate.com;
    ssl_certificate /etc/nginx/certs/cloudflare_chain.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;

    location / {
        proxy_pass http://172.17.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
