listening-port=3478
tls-listening-port=5349

realm=longdcam.ghmate.com

use-auth-secret
static-auth-secret=CHANGE_ME_TURN_SECRET

min-port=40000
max-port=40100

fingerprint
lt-cred-mech

no-cli
no-tlsv1
no-tlsv1_1

log-file=stdout
verbose
